# ----------------------- #
#      Main Configs       #
# ----------------------- #
url:          link-webcreations.github.io/juetpy/
author:       Yves ANDOLFATTO
description:  Blog du voyage en am√©rique du sud

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

paginate:           5
pagination_roots:   ['/articles']
markdown:           rdiscount
exclude:            ["README.md", "CNAME", "Gemfile", "vendor"]
gallery:
    dir:            photos
    title:          "PhotosTiiiiitre"
    title_prefix:   "PrefixFotoooo: "

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

disqus_short_name: juetpy
google_analytics_tracking_id: UA-XXXXX-X
